=== TuftsUniversity/sabt/schema/rsa.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xsd:schema elementFormDefault="qualified" version="1.0"
	    xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:include schemaLocation="sa_common.xsd" />

  <xsd:complexType name="rsaDoc">
    <xsd:sequence>
      <xsd:element name="history">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="activation" type="xsd:date" minOccurs="0" />
            <xsd:element name="producerEndorsement" type="xsd:date" />
            <xsd:element name="archiveEndorsement" type="xsd:date" />
            <xsd:element name="expiration" type="xsd:date" minOccurs="0" />
            <xsd:element name="audit">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="created" type="auditDate" minOccurs="0" />
                  <xsd:element name="edited" type="auditDate" minOccurs="0" maxOccurs="unbounded" />
                  <xsd:element name="committed" type="auditDate" minOccurs="0" />
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>

      
      <!-- ### Archive -->
      
      <!--     Archive ID -->
      <xsd:element name="archiveId" type="xsd:string" />
      
      <!--     Warrant to Collect -->
      <xsd:element name="warrantToCollect" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
      
      <!-- ### Ingest Project Management -->

      <!--     Accession Number -->
      <xsd:element name="accessionNumber" type="xsd:string" minOccurs="0" />
      
      <!--     Activity Log Number -->
      <xsd:element name="activityLogNumber" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
      
      <!--     Survey Report ID -->
      <xsd:element name="surveyReportId" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
      
      
      <!-- ### Producer -->
      
      <!--     Records Creator Records -->
      <xsd:element name="recordsCreator" type="producer" maxOccurs="unbounded" />

      <!--     Record Producer -->
      <xsd:element name="recordsProducer" type="producer" maxOccurs="unbounded" />
      
      <!--     Recordkeeping System -->
      <xsd:element name="recordkeepingSystem" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
      

      <!-- ### Records -->

      <!--     General Records Description -->
      <xsd:element name="generalRecordsDescription" type="xsd:string" />

      <!--     Record Type Record -->
      <xsd:element name="recordType" type="xsd:string" />
      
      <!--     Format Type -->
      <xsd:element name="formatType" type="xsd:string" maxOccurs="unbounded" />

      <!--     Date Span -->
      <xsd:element name="dateSpan" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:attribute name="start" type="datePartial" use="required" />
          <xsd:attribute name="end" type="datePartial" use="required" />
        </xsd:complexType>
      </xsd:element>
      
      <!--     Extent -->
      <xsd:element name="extent" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:attribute name="units" type="xsd:string" use="required" />
          <xsd:attribute name="value" type="xsd:float" use="required" />
        </xsd:complexType>
      </xsd:element>


      <!--     Copyright -->
      <xsd:element name="copyright" type="xsd:string" maxOccurs="unbounded" />
      
      <!--     Access -->
      <xsd:element name="access" type="xsd:string" maxOccurs="unbounded" />
      
      <!--     Arrangement and Naming Scheme -->
      <xsd:element name="arrangementAndNamingScheme" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
      
      <!--     Retention Period -->
      <xsd:element name="retentionPeriod" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />

      <!--     Retention Alert Date -->
      <xsd:element name="retentionAlertDate" type="xsd:date" minOccurs="0" maxOccurs="unbounded" />
      
      <!--     SIP Creation and Transfer -->
      <xsd:element name="sipCreationAndTransfer" type="xsd:string" maxOccurs="unbounded" />
      
      <!--     SIP transfer drop box location -->
      <xsd:element name="dropboxUrl" type="xsd:anyURI" maxOccurs="unbounded" />
      
      <!--     Transfer Date -->
      <xsd:element name="transferDate" type="xsd:date" />
      
      <!-- ### Archival Management -->

      <!--     SIP to AIP -->
      <xsd:element name="sipToAip" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />

      <!--     Archival Description Standard -->
      <xsd:element name="archivalDescriptionStandard" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
      
      <!--     Respect de Fonds -->
      <xsd:element name="respectDeFonds" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />

    </xsd:sequence>

    <xsd:attribute name="schemaVersion" type="xsd:token" use="required" />
    <xsd:attribute name="id" type="xsd:ID" use="required" />
    <xsd:attribute name="standing" type="xsd:IDREF" />
  </xsd:complexType>
  
  <xsd:element name="regularSubmissionAgreement" type="rsaDoc" />
  
</xsd:schema>

=== TuftsUniversity/sabt/schema/example/minimal_rsa.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
This is a minimal RSA file. It does not include several elements that the
schema lists as optional.
It is suitable for use as testing against the the output of the Submission
Agreement Builder tool.
-->

<regularSubmissionAgreement
   xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" 
   xsd:noNamespaceSchemaLocation="rsa.xsd"
   schemaVersion="1.0"
   id="minimal-RSA2009-01">

  <!-- Submission Agreement Management -->
  <history>
    <producerEndorsement>2009-02-09</producerEndorsement>
    <archiveEndorsement>2009-02-09</archiveEndorsement>
    <audit />
  </history>
  
  <!-- Archive -->
  <archiveId>Digital Collections and Archives, Tufts University</archiveId>
  
  <!-- Producer -->
  <recordsCreator id="RC0034" />
  <recordsProducer>Department of Widget Science, Tufts University</recordsProducer>
  
  <!-- Records -->
  <generalRecordsDescription>Paragraph goes here.</generalRecordsDescription>
  <recordType>910 Meeting Minutes and Agenda, http://dca.tufts.edu/?pid=63#rs910</recordType>
  <formatType>PDF/A</formatType>
  <dateSpan start="1995" end="2001" />
  <extent value="12" units="cu. ft." />
  <copyright>Copyright holder: Allen Anderson. Licensing Agreement with Archive: See Anderson-DCA_copyrightlicense_2008-12-12.pdf</copyright>
  <access>Category 3: General University Records, Closed 20 years from records creation. http://dca.tufts.edu/?pid=17</access>
  
  <!-- Producer to Archive -->
  <sipCreationAndTransfer>Transfer 100 image files as tifs along with inventory and descriptive metadata; place files in electronic dropbox at http://foo</sipCreationAndTransfer>
  <dropboxUrl>http://example.com/dropbox</dropboxUrl>
  <transferDate>2009-02-09</transferDate>
  
</regularSubmissionAgreement>

=== TuftsUniversity/sabt/TAPER/t/rsa/widgets.xml
<?xml version="1.0" encoding="utf-8"?>

<!--
This is a minimal RSA file. It does not include several elements that the
schema lists as optional.
It is suitable for use as testing against the the output of the Submission
Agreement Builder tool.
-->

<!--
 * COPYRIGHT:
 *
 * Copyright 2010, 2011 Tufts University.
 *
 *
 * FUNDING:
 *
 * The development of the TAPER software suite was funded by the
 * National Historic Publications and Records Commission (NHPRC).
 * Grant number RE10005-08.
 *
 *
 * LICENSE:
 *
 * This file is part of the TAPER software suite.
 *
 * The TAPER software suite is free software: you can redistribute
 * it and/or modify it under the terms of the GNU Affero General
 * Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later
 * version.
 *
 * The TAPER software suite is distributed in the hope that it will
 * be useful, but WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public
 * License along with the TAPER software suite.  If not, see
 * <http://www.gnu.org/licenses/>.
 -->

<regularSubmissionAgreement
   xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" 
   xsd:noNamespaceSchemaLocation="rsa.xsd"
   schemaVersion="1.0"
   id="RSA2009-01" standing="SA2009-01">

  <!-- Submission Agreement Management -->
  <history>
    <activation>2009-02-09</activation>
    <producerEndorsement>2009-02-09</producerEndorsement>
    <archiveEndorsement>2009-02-09</archiveEndorsement>
    <audit>
      <created date="2009-02-01" by="Test Tester" />
      <committed date="2009-02-09" by="Test Tester" />
    </audit>
  </history>
  
  <!-- Archive -->
  <archiveId>Digital Collections and Archives, Tufts University</archiveId>
  <warrantToCollect>University Records Policy, http://dca.tufts.edu/?pid=19</warrantToCollect>
  
  <!-- Producer -->
  <recordsCreator id="RC0034">RC0034</recordsCreator>
  <recordsProducer>Department of Widget Science, Tufts University</recordsProducer>
  <recordkeepingSystem>RK0009</recordkeepingSystem>
  
  <!-- Records -->
  <generalRecordsDescription>Paragraph goes here.</generalRecordsDescription>
  <recordType>910 Meeting Minutes and Agenda, http://dca.tufts.edu/?pid=63#rs910</recordType>
  <formatType>photographic_prints</formatType>
  <formatType>digital_media</formatType>
  <dateSpan start="1995" end="2001" />
  <extent value="12" units="cu. ft." />
  <copyright>Copyright holder: Allen Anderson. Licensing Agreement with Archive: See Anderson-DCA_copyrightlicense_2008-12-12.pdf</copyright>
  <access>Category 3: General University Records, Closed 20 years from records creation. http://dca.tufts.edu/?pid=17</access>
  <arrangementAndNamingScheme>chronological</arrangementAndNamingScheme>
  <retentionPeriod>Retain Close of Grant Project + 7 Years, then confidentially destroy. Director of the Archive and Professor John Johnson, Department of Widget Science review records before executing disposition.</retentionPeriod>
  
  <!-- Producer to Archive -->
  <sipCreationAndTransfer>label_box</sipCreationAndTransfer>
  <sipCreationAndTransfer>create_inventory</sipCreationAndTransfer>
  <dropboxUrl>http://example.com/dropbox</dropboxUrl>
  <transferDate>2009-02-09</transferDate>
  
  <!-- Archive Management -->
  <sipToAip>Maintain tifs, create full and thumbnail datastreams</sipToAip>
  <archivalDescriptionStandard>Encoded Archival Description (EAD). http://www.loc.gov/ead/</archivalDescriptionStandard>
  <respectDeFonds>UA041 Department of Widget Science records</respectDeFonds>

</regularSubmissionAgreement>

=== TuftsUniversity/sabt/schema/example/rsa.xml
<?xml version="1.0" encoding="utf-8"?>
<regularSubmissionAgreement
   xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" 
   xsd:noNamespaceSchemaLocation="rsa.xsd"
   schemaVersion="1.0"
   id="RSA2009-01" standing="SSA2009-01">

  <!-- Submission Agreement Management -->
  <history>
    <activation>2009-02-09</activation>
    <producerEndorsement>2009-02-05</producerEndorsement>
    <archiveEndorsement>2009-02-09</archiveEndorsement>
    <expiration>2009-10-23</expiration>
    <audit>
      <created date="2009-02-01" by="Test Tester" />
      <edited date="2009-02-02" by="Test Tester" />
      <edited date="2009-02-03" by="Someone Else" />
      <committed date="2009-02-09" by="Test Tester" />
    </audit>
  </history>
  
  <!-- Archive -->
  <archiveId>Digital Collections and Archives, Tufts University</archiveId>
  <warrantToCollect>University Records Policy, http://dca.tufts.edu/?pid=19</warrantToCollect>
  
  <!-- Ingest Project Management -->
  <accessionNumber>2010.024</accessionNumber>
  <activityLogNumber>j2010.085</activityLogNumber>
  <surveyReportId>SR2010.011</surveyReportId>

  <!-- Producer -->
  <recordsCreator id="RC0034" email="dws@tufts.edu">Department of Widget Science, Tufts University</recordsCreator>
  <recordsProducer id="RC0034" email="dws@tufts.edu">Department of Widget Science, Tufts University</recordsProducer>
  <recordkeepingSystem>RK0009</recordkeepingSystem>
  
  <!-- Records -->
  <generalRecordsDescription>Paragraph goes here.</generalRecordsDescription>
  <recordType>910 Meeting Minutes and Agenda, http://dca.tufts.edu/?pid=63#rs910</recordType>
  <formatType>PDF/A</formatType>
  <dateSpan start="1995" end="2001" />
  <extent value="12" units="cu. ft." />
  <extent value="55" units="MB" />
  <extent value="7" units="CDs" />
  <copyright>Copyright holder: Allen Anderson. Licensing Agreement with Archive: See Anderson-DCA_copyrightlicense_2008-12-12.pdf</copyright>
  <access>Category 3: General University Records, Closed 20 years from records creation. http://dca.tufts.edu/?pid=17</access>
  <arrangementAndNamingScheme>Department of Widget Science naming scheme at Widget_namingscheme.doc</arrangementAndNamingScheme>
  <retentionPeriod>Retain Close of Grant Project + 7 Years, then confidentially destroy. Director of the Archive and Professor John Johnson, Department of Widget Science review records before executing disposition.</retentionPeriod>
  <retentionAlertDate>2012-10-20</retentionAlertDate>
  
  <!-- Producer to Archive -->
  <sipCreationAndTransfer>Transfer 100 image files as tifs along with inventory and descriptive metadata; place files in electronic dropbox at http://foo</sipCreationAndTransfer>
  <dropboxUrl>http://example.com/dropbox</dropboxUrl>
  <transferDate>2009-02-09</transferDate>
  
  <!-- Archive Management -->
  <sipToAip>Maintain tifs, create full and thumbnail datastreams</sipToAip>
  <archivalDescriptionStandard>Encoded Archival Description (EAD). http://www.loc.gov/ead/</archivalDescriptionStandard>
  <respectDeFonds>UA041 Department of Widget Science records</respectDeFonds>

</regularSubmissionAgreement>
